
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-automation.html
  extra_module_url:
    - /local/cards/card-mod.js

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry to enable the cloud component
#cloud:



recorder:
    db_url: mysql://homeassistant:235edfge&AF7vh(aghsdsf@core-mariadb/homeassistant?charset=utf8mb4
    purge_keep_days: 2
    include:
        domains:
         - light
         - sensor
         - binary_sensor
         - person
    exclude: 
        entity_globs:
        - number.micro_threshold_*
        - number.macro_threshold_*
        - sensor.roomsense_macrobin*
        - sensor.roomsense_microbin*
        - sensor.*bin*_*
        - sensor.chart*
        - sensor.*_distance_*

template:
  - sensor:
      - name: "chart11"
        state: |
              {{  now()    }}
        attributes:
            Heights: |
                  {% set entities=["number.roomsense_macrothreshold0_f412fad7b074","number.roomsense_macrothreshold1_f412fad7b074","number.roomsense_macrothreshold2_f412fad7b074","number.roomsense_macrothreshold3_f412fad7b074","number.roomsense_macrothreshold4_f412fad7b074","number.roomsense_macrothreshold5_f412fad7b074","number.roomsense_macrothreshold6_f412fad7b074","number.roomsense_macrothreshold7_f412fad7b074","number.roomsense_macrothreshold8_f412fad7b074"] %}
                  {{ entities | map('states') | list       }}

      - name: "chart12"
        state: |
              {{  now()    }}
        attributes:
            Heights: |
                  {% set entities=["sensor.roomsense_macrobin0_f412fad7b074","sensor.roomsense_macrobin1_f412fad7b074","sensor.roomsense_macrobin2_f412fad7b074","sensor.roomsense_macrobin3_f412fad7b074","sensor.roomsense_macrobin4_f412fad7b074","sensor.roomsense_macrobin5_f412fad7b074","sensor.roomsense_macrobin6_f412fad7b074","sensor.roomsense_macrobin7_f412fad7b074","sensor.roomsense_macrobin8_f412fad7b074"] %}
                  {{ entities | map('states') | list       }}

      - name: "chart21"
        state: |
              {{  now()    }}
        attributes:
            Heights: |
                  {% set entities=["number.roomsense_microthreshold0_f412fad7b074","number.roomsense_microthreshold1_f412fad7b074","number.roomsense_microthreshold2_f412fad7b074","number.roomsense_microthreshold3_f412fad7b074","number.roomsense_microthreshold4_f412fad7b074","number.roomsense_microthreshold5_f412fad7b074","number.roomsense_microthreshold6_f412fad7b074","number.roomsense_microthreshold7_f412fad7b074","number.roomsense_microthreshold8_f412fad7b074"] %}
                  {{ entities | map('states') | list       }}
                  
      - name: "chart22"
        state: |
              {{  now()    }}
        attributes:
            Heights: |
                  {% set entities=["sensor.roomsense_microbin0_f412fad7b074","sensor.roomsense_microbin1_f412fad7b074","sensor.roomsense_microbin2_f412fad7b074","sensor.roomsense_microbin3_f412fad7b074","sensor.roomsense_microbin4_f412fad7b074","sensor.roomsense_microbin5_f412fad7b074","sensor.roomsense_microbin6_f412fad7b074","sensor.roomsense_microbin7_f412fad7b074","sensor.roomsense_microbin8_f412fad7b074"] %}
                  {{ entities | map('states') | list       }}

lovelace:
  mode: storage
  dashboards:
    lovelace-roomsense:
      mode: yaml
      title: RoomSense IQ
      icon: mdi:script
      show_in_sidebar: true
      filename: dashboards.yaml
  resources:
    - url: /local/cards/card-mod.js
      type: module
    - url: /local/cards/apexcharts-card.js
      type: module
    - url: /local/cards/numberbox-card.js
      type: module
    - url: /local/cards/mini-graph-card-bundle.js
      type: module
    - url: /local/cards/slider-entity-row.js
      type: module
    - url: /local/cards/button-card.js
      type: module
      
      
